namespace DevToys.PocoDB.RandomData
{ 
    internal static class Companies
    {
        public static readonly string[] Items = new string[] {
            "GeniusMatcher","CaroGen","AboutMyStar","Stayful","Stratio","PsomasFMG","Yaphie","Radiojar","SideStripe","Nerd",
            "Mosec","mySupermarket","Precision","Biocrates","Pososhok.ru","Pure","Jenkins"," Inc.","TradeGlobal","Voodle",
            "Salient"," Inc. (Villij.com)","CTQuan","Newsy","Tunii","Nunook","Pull","Broccol-e-games","bodaplanes","Fairwinds",
            "ProxiVision","Drivewyze","PingStamp","Eyegroove","Bootstrap","Finding","OnTrack","Runnable"," Inc.","Alea",
            "rubberit","Accurence","Centrillion","FirstString","Pushing","Wilocity","Silverback","MedCenterDisplay","Cream","StyleQ",
            "Sparktrend","YouGift","HobbyTalk","GuidesMob","LookAcross","Taiga","Virtual","Integrated","VanDyne","Dating",
            "Zumi","TapFame","Netstory","LaticÃƒÂ­nios","Tripbirds","Filtec","Upstream","HealthDataInsights","Yippy","Green",
            "ATOMOO","Real","Alga","TappIn","Crescentrating","Right","Geminare","TweetMySong.com","truedash","VISENZE",
            "Storm","ChowNow","Velsys","Evikon","Lithera","Radio","The","Evalve","Socrative","Entelo",
            "Handy","Compliance","Squareknot","GoCoin","Alicanto","Traity","SL","Project","Ingen.io","HexAirbot",
            "anchor.travel","IceCure","Mind","Takeaway.com","Seesaw","Bettery","Wadaro","Mieple","Charleston","Shopsy",
            "Macrotherapy","Aireum","MedSolutions","Yonja","Iceotope","Superbly","Vendsy","ExploraMed","Youbei","CompuPay",
            "jiffstore","OwlTing","Nest","Raven","ZAOZAO","TopCat","Treasure","Prosonix","Splitforce","Foradian",
            "EyeJot","PipelineDB","Lightwaves","MAR","Transfluent","Intellihot","osmogames.com","AutoShag","Meta","HotPads",
            "SecretBuilders","Frayman","Braintech","Advanced","ShomoLive","Genesis","Podaddies","Superbly","WebMarketing","Courion",
            "Wikibon","C9","QUICK","Datappraise","Visionary","Inside","Standout","SurfAir","Telos","Ticketfly",
            "CriticalArc","Efficient","RiffTrax","Synageva","Launchups","TastingRoom.com","Mobiclip","Accelalox","BeiBei","XCEL Healthcare",
            "Crescendo","Talent","Sensorist","Ninsight","iTagged","BookNow","Lumaqco","Monster","Viridis","Pheedo",
            "CV","Applied","RMI","Odimax","Gracelock","Ceragon","Wevod","Edusoft","Navini","Konbini",
            "Odysii","Smash","Darberry","PixSense","Coastal","Liquiteria","Nourish","eTutor","mobiManage","Vacation",
            "Snapsort","Picaboo","S.E.A.","Yatown","Zomato","Blued","Health","BioDigital","SkyRide"," Inc.",
            "Uvinum","eelusion","Tubaloo","Credport","Plaid","Castle","Metanautix","Bondora","Let","FND",
            "TrialBee","Etable","Isabella","Oversee","Gruppo","InMage","OrthoHelix","Billibox","IMshopping","WadeCo",
            "Mediamorph","Cyberlightning","4th","Actions","Telly","","FoneSense","Scirra","OmegaGenesis"," Inc.",
            "Sirenza Microdevices","TechLive","Le"," Inc.","mobintent","Getup","Trellia","AccessPay","Zwipe","agreement24",
            "WellMetris","Leadhit","Soulstice","Dering","ADVENTRX","MagicEvent","Customer","Bizily","One97","NeoEdge",
            "Little","Energeno","Quantagen","Swink.tv","Exos","RABT","eBaoTech","TopVisible","Globecon","beenz.com",
            "Suneva","Skubana","Mailcloud","Discovery","MicroSense","All","Sparkcloud","Pricing","Automsoft","ADOMIC",
            "MedMark","Omniox","Binpress","HealthPrize","Zeetl","Amigos","InfernoRed","Signal","ZeniMax","Glaukos",
            "GlassesGroupGlobal","CRISPR","Buzzoole","Agistics","Scopis"," Inc.","CertiVox","Paxfire","Kohort","TapCommerce",
            "BadAbroad","99tests","Plink","Tyto","Cook123","Cldi","Wonder","MutualMind","Qonf","yWorld",
            "Radio","Millican","Aimetis","Nexus","AnySource","Tongtech","CityAds","fluIT","Tangentix","DoubleBeam",
            "EventRegist","Letsdecco","Trelligence","24h00","SAY","Oriel","PetroDE","LearnUpon","Lion","AGILE",
            "Tolerx","Cingulate","Crossborders","Deltagen","Virtual","Massive","wali","Convertio","Cloudant","St.",
            "Autowatts","Taqua","Avontrust","365","Perpetuuiti","SpeechTrans","ClickN","Moasis","Xuanyixia","thephotocloser.com",
            "Gecko","Synker","SMSA","Dajiabao","MTX","obiwon","BlueView","Play","Certus","Nature's",
            "Medify","Linko","Attensity","Plix","Biorasis","Metaweb","Funifi","Sophiris","Pikanote","Mformation",
            "Viewpoint","WowOwow","CAD","AGILE","cinvolve","Ismole","iCrumz","TRAN.SL","Gooddler","Visionarity",
            "Johns","BigBad","Loveland","Optimal","Qoiza","All","Health","Zapstitch","Poppin","FUZE",
            "iCIMS","eVenues","Allovue","nuvoTV","Exhale","NextHop","Silere","Innotas","True","Blaze",
            "Leartieste","HapBoo","Trendlr","Jammin","VirtualWorks","GroupFlier","Rakuten","Sensorflare","Any+Times","Boyibang",
            "COUPIES","DemystData","Femasys","DanceJam","Bridesandlovers.com","Insys","ZangZing","Kamego","WorkSnug","ARTtwo50",
            "CeQur","GenSight","BusyFlow","FounderFuel","Buytech","Perfecto","Vidatronic","MetroFlats.com","S*Bio","Neema",
            "PlayerDuel","Yieldbot","Zend","DOCUSYS","Keystone","aTyr","Crowd","Applix","ProPlan","Fronto",
            "GateGuru","OnPath","Virtual","Mirubee","BreakingPoint","CitiVox","YOGITECH","Starriser","Lastline","theAudience",
            "NuLabel","Forum","Journalism","StudioNow","Webymaster","Cabeo","Dime","myRete","Figure","Excelimmune",
            "Ipsat","Circle","Admittor","LanternCRM","Kite","Data","directworx","Aqua","Sepior","Apartama",
            "Cubby","Vicor","shopa","Peekaboo","RoleStar","MinoMonsters","IHS","Nifty","ConsortiEX","Wistia",
            "Plazes","Blackbay","Apptive","Theorem","XOR.MOTORS","General","MetaCert","Chef","EveryMove","Forerun",
            "SVAS","PeakStream","Screen","Hoverink","Tribridge","Cine-tal","Nitro","kinkon","Averail","Tyros"
        };
    }
}
