namespace DevToys.PocoDB.RandomData
{
    internal static class LastNames
    {
        public static readonly string[] Items = new string[] {
            "Geerling","Martel","Beeck Beeckmans","Billung","van Ruijs","Gulcher","Wouters","Gratie","Beijring",
            "Bruynzeels","Mercks","Hakker","van Coret-Coredo","Bosch","Verschuere","Vervoort","Klerks","Zijlemans",
            "van der Latier","Schwartsbach","Barents","Osterhoudt","Knuf","Fleche","Luc","Schiffer",
            "van der Reimes","Noordeloos","Wessex","Korstman","Kerkhof","Schulten","Neuzerling","Eckhardt","Bernicia",
            "Poncelet","Dubois","Duvenvoirde","Waardeloo","Suijker","Ketel","Wolffel","Simons","Niermann",
            "van Lucel","Haarlem","Meyer","Parijs","Scherms","Aertsz (Heerschop)","Meijer","van Boetet",
            "Blom","Jansen","Huijben","Hoeven","de Leene",
            "van Goderts","Pieters","Hulskes","Gent","Guellec","Hermans","Thomas","Demmendaal",
            "van Persijn","Oosten","Moensendijk","Geertsen","Schotte","Huijbrechts","Liendert","Hazenveld","Schuurmans",
            "Schiffer","Bastiaanse","Koster","Nihoe"," van 't Passchiers",
            "Mathol","Wassenaar","Zijlmans","Suijker","Gerrits",
            "Volcke","Hoevel en van Zwindrecht","Verbeek"," der","Coreth von und zu Coredo und Starkenberg","Lonen","Verdun",
            "Zwart","Bave","Reimes","Kuijpers","Everde (Kapteijn)","Vertoor(e)n","Noordeloos",
            "Linschoten","Neuteboom","Oostveen","Huls",
            "Wassenaar","Kolen","Potters","Bertho","Knuf","Romijn","Wever","Kamp","Rietveld","Mathol",
            "Dam","Kathagen","Boeser"," le","Levesque","Verwoert","Kortman",
            "Grondelle","Gellemeyer","Aelftrud van Wessex","Die Bont","Reijers","Noordeloos","Gils","Bloemendaal","Gemert",
            "Schenkel","Uphus"," den","Lage","Perkins","Wildschut","Françoise",
            "Liendert","Schotte","Steen","Klashorst"," ter","Leguit","Govarts","Geldens","Janse",
            "Susa","Rossum","Schagen","Leuven","Haeften",
            "Kisman","Herstal","Kirpenstein","Boulogne","Holland","Rek","Heripon","Waltrade Walderade",
            "Martel","Ghoerle","Noordijk","Lambers","Jong","Overeem","Ploeg","Scuylenborchs",
            "Bresé","Wright","Ramaker","Noordijk","Brand","Beernink","Gratie",
            "Corput","Nihoe","Serra","Otte","Jacobi","Embden","Boer",
            "Doornhem","Lemmens","Hagen","Weterink","Brievingh","Man",
            "Schenkel","Spreeuw","Leek","Rademaker","Knuf","Pratt","Ridder","Karels",
            "Hellevoort","Nes","Bierstraten","Verbeeck","Werl-Arnsberg","Teunissen","Steenbakkers","Geertsen",
            "Bouthoorn","Bernicia","Kint","Michiels","Bergen","Köster","Middelkoop","Saksen",
            "Bijlsma","Geldens","Bloemendaal","Formbach","Parijs","Guit",
            "Nuwenhuysen","Nieuwenhuijsen","Luitgardis van Neustrië","Mare","Takkelenburg","Jong","Soest",
            "Alenburg","Plantard","Gemert","Lucel","Kok","Corput","Draaisma","Vos","Coreth von und zu Coredo und Starkenberg",
            "Jacobi"," le","Heyne","Karels","Hekker","Kof","Zevenboom",
            "Velthoven","Stinis","Dam","Laffray","Moene(n)","Janssen","Oversteeg","Verheuvel",
            "Woudenberg","Doornhem","Bergen","Roosenboom","Hendriks","Neuzerling","Pluijm","Wright","Vial",
            "Vrome","Bruin","Diesbergen","Verhaar","Broek","Mansvelt","Olykan","Horst",
            "Duvenvoirde","Brenen","Thout","Schilt","Leeuwen"," van 't","Boers",
            "Niermann","Glasses","Uphaus","Embden","Klerks","Guit","Eck","Amalrada",
            "Kosten","Blokland","Poppel","Roos","Oever","Nijs","Korstman",
            "Rotteveel","Gnodde","Nieuwenhuijsen"," le","Geenen","Terry","Mathurin",
            "Timmerman","Ruijs","Vergeer","Goedhart","Sterkman","Graaf","Hemert",
            "Northeim","Fremie","Keltenie","Hoevel en van Zwindrecht","Keijzer","Lucel","Scholten","Blewanus","Dachgelder",
            "Kuijpers","Claesner","Keijzer","Geerling","Wilcken","Haneberg","Nyeuwenhuysen","Beer",
            "Verbeeck","Duyvenvoorde","Kijnder","Mispelen","Dijk","Uit de Willigen","Massa","Jacobs",
            "Vial","Hemert","Geneart","Waarbeek","Steenbeek"," le"," 's-","Vermandois","Dennenberg","Gemen",
            "Gastel","Leeuwen","Dommelen","Pauw","Boulogne","Walsteijn","Potters","Grondelle","Egisheim"
        };
    }
}
